platform :ios, '11.0'

target 'BeeHive-Swift' do
  use_frameworks!
  pod 'ToyBrick', :path=>'../'
  pod 'Module001', :path=>'./Module001'
  pod 'Module002', :path=>'./Module002'
  pod 'Middle', :path=>'./Middle'

end
